# KM-A Job List Report
dox:
    baseurl:
    title: KM-A Job List Report
    theme_color: '#0976f8' # Define theme primary color with HEX value
    language: en-US # Use ISO language and country codes to setup language of your website - https://www.w3schools.com/tags/ref_language_codes.asp and https://www.w3schools.com/tags/ref_country_codes.asp
    header:
        logo:
            text: KM-A 
            image:
        nav:
            - item_name: Homepage
              item_url: /
            - item_name: Default Layout
              item_url: /default
        cta:
            label: Documentation
            url: /documentation
            icon: folder # list of all icons - https://feathericons.com
    footer:
        logo:
            text: KM-A Job List Report
            image:
        text:  Copyright &copy; © 2019. BOBICA KMC-IIMMSS 4.0, <br> KM-Croatia, Ul. dr. Otmar Zwiebelhofer 3, 10 451 Pisarovina. All Rights Reserved.
    google_analytics:
        tracking_code: # GA tracking code 
    comments:
        disqus_forum_shortname: # Disqus forum shortname

# Defining collections
collections:
    documentation:
        output: true

# Defining defaults
defaults:
    -
        scope:
            path: ''
            type: 'documentation'
        values:
            layout: 'documentation-single'

# SASS settings
sass:
    sass_dir: ./dox-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./dox-theme/_layouts
includes_dir: ./dox-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
